DROP TABLE roles CASCADE;
DROP TABLE heroes CASCADE;
DROP TABLE affiliations CASCADE;
DROP TABLE heroes_affiliations CASCADE;
DROP TABLE weapons CASCADE;
DROP TABLE heroes_weapons CASCADE;
DROP TABLE abilities CASCADE;
DROP TABLE heroes_abilities CASCADE;